### ISSUE TITLE
pythonでelasticsearchが叩けない

### ISSUE THREAD

**Issue by ghost** [Amano123/elasticsearch_ubuntu18.04#1]
>>> print(es.indices.exists(index="aa"))
Traceback (most recent call last):
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amano/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 242, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/home/amano/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f270c21deb8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amano/.local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/amano/.local/lib/python3.6/site-packages/elasticsearch/client/indices.py", line 294, in exists
    return self.transport.perform_request("HEAD", _make_path(index), params=params)
  File "/home/amano/.local/lib/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/amano/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 254, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f270c21deb8>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f270c21deb8>: Failed to establish a new connection: [Errno 111] Connection refused)
>>>

**Comment by Amano123** [comment]
プログラムコード全文乗せてくれるとありがたいです。

**Comment by ghost** [comment]
import elasticsearch
from elasticsearch import Elasticsearch, helper
es = elasticsearch()

print(es.indices.exists(index="aa"))

です。
これで、Falseが帰ってきて欲しいのですが。

**Comment by Amano123** [comment]
ホストを指定していないのでエラーが出ていると考えられます。
複数のコンテナを起動していますが、ネットワークが生成されているのでコンテナネームを指定するだけで使える様になると思います。

```python
from elasticsearch import Elasticsearch
es = Elasticsearch("elasticsearch")
print(es.indices.exists(index="aa"))
```

このプログラムでFalseが帰ってくるともいます。
READMEにも書いておきます。
